version: '3'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    tty: true
    ports:
      - '8080:8080'
    command: go run main.go
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./docker/db/init:/docker-entrypoint-initdb.d
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./tmp/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
